steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/thohcm-backend:$BUILD_ID'
      - './backend'
    id: 'build-backend'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/thohcm-backend:$BUILD_ID'
    id: 'push-backend'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'thohcm-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/thohcm-backend:$BUILD_ID'
      - '--region'
      - 'asia-southeast1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '4Gi'
      - '--cpu'
      - '4'
      - '--max-instances'
      - '5'
      - '--min-instances'
      - '1'
      - '--concurrency'
      - '80'
      - '--timeout'
      - '300'
      - '--service-account'
      - 'thohcm-storage@thohcm-application-475603.iam.gserviceaccount.com'
      - '--set-env-vars'
      - 'NODE_ENV=production,GCS_BUCKET_NAME=thohcm-storage,MONGODB_URI=${_MONGODB_URI},JWT_SECRET=${_JWT_SECRET},REDIS_HOST=10.106.178.204,REDIS_PORT=6379'
    id: 'deploy-backend'

# Store images in Container Registry
images:
  - 'gcr.io/$PROJECT_ID/thohcm-backend:$BUILD_ID'

# Build options
options:
  logging: CLOUD_LOGGING_ONLY